// Generated by CoffeeScript 1.4.0
(function() {
  var inspect;

  inspect = require('util').inspect;

  exports.generator = require('./algorithm');

  exports.createMarket = function(options) {
    var code, codes, randInt, server, tickers, updateInterval, _i, _len, _ref, _ref1, _ref2;
    if (options == null) {
      options = {};
    }
    server = (_ref = options.server) != null ? _ref : 'geekdaq';
    codes = (_ref1 = options.tickers) != null ? _ref1 : [];
    updateInterval = (_ref2 = options.updateInterval) != null ? _ref2 : 500;
    randInt = function(min, max) {
      return Math.round(min + Math.random() * (max - min));
    };
    tickers = {};
    for (_i = 0, _len = codes.length; _i < _len; _i++) {
      code = codes[_i];
      tickers[code] = {
        func: Geekdaq.generator({
          range: 5,
          levels: 150
        }),
        price: randInt(100, 400),
        volume: randInt(100000, 400000)
      };
    }
    repeat(updateInterval, function() {
      var ticker, _results;
      _results = [];
      for (code in tickers) {
        ticker = tickers[code];
        _results.push(ticker.price += ticker.func());
      }
      return _results;
    });
    return {
      symbols: function() {
        return symbols;
      },
      tickers: function() {
        return tickers;
      },
      ticker: function(code) {
        return tickers[code];
      }
    };
  };

}).call(this);
