// Generated by CoffeeScript 1.4.0
(function() {
  var debug, delay, generator, inspect, pretty, randInt, repeat, symbol, symbols, tickers, _i, _len;

  inspect = require('util').inspect;

  generator = require('./algorithm');

  debug = function(msg) {
    if (true) {
      return console.log(msg);
    }
  };

  pretty = function(obj) {
    return "" + (inspect(obj, false, 20, true));
  };

  delay = function(t, f) {
    return setTimeout(f, t);
  };

  repeat = function(t, f) {
    return setInterval(f, t);
  };

  randInt = function(min, max) {
    return Math.round(min + Math.random() * (max - min));
  };

  symbols = ['JS', 'LISP', 'PERL', 'RUBY', 'NET', 'JAVA', 'CAFE'];

  tickers = {};

  for (_i = 0, _len = symbols.length; _i < _len; _i++) {
    symbol = symbols[_i];
    tickers[symbol] = {
      func: generator({
        range: 5,
        levels: 150
      }),
      price: randInt(50, 400)
    };
  }

  console.log(Object.keys(tickers).join(','));

  repeat(5, function() {
    var name, ticker, values;
    values = (function() {
      var _results;
      _results = [];
      for (name in tickers) {
        ticker = tickers[name];
        ticker.price += ticker.func();
        _results.push(ticker.price);
      }
      return _results;
    })();
    return console.log(values.join(','));
  });

}).call(this);
